# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Start jksb

on:
  workflow_dispatch:
  schedule:
    - cron: '35 20,22,23,5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start jksb Direct.
      env:
        mail_id: ${{secrets.mail_id}}
        mail_pd: ${{secrets.mail_pd}}
        target_admin_addr: ${{secrets.admin_mail_id}}
        processing_pool: ${{secrets.processing_pool}}
      run: |
        python Application.py "$mail_id" "$mail_pd" "$target_admin_addr" "$processing_pool"
